version: '3.4'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  multimedia-users-api:
    build:
      context: .
      dockerfile: Multimedia.Users/Dockerfile
    depends_on:
      - ms-sql-server
    environment:
      - ConnectionStrings__UsersMultimediaDockerCS=Server=ms-sql-server,1433;Initial Catalog=UsersMultimediaDB;User ID=SA;Password=P@ssw0rd;TrustServerCertificate=true;Encrypt=False;
      - JwtToken__TokenIssuer=MultimediaUsersApi
      - JwtToken__Key=THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET, IT CAN BE ANY STRING
    ports:
      - "8080:80"
  multimedia-images-api:
    build:
      context: .
      dockerfile: Multimedia.Images/Dockerfile
    depends_on:
     - ms-sql-server
    environment:
     - ConnectionStrings__ImagesMultimediaDockerCS=Server=ms-sql-server,1433;Initial Catalog=ImagesMultimediaDB;User ID=SA;Password=P@ssw0rd;TrustServerCertificate=true;Encrypt=False;
     - JwtToken__TokenIssuer=MultimediaImagesApi
     - JwtToken__Key=THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET, IT CAN BE ANY STRING
    volumes:
      - ./Repository_Images:/app/Repository_Images
    ports:
      - "8081:80"
  multimedia-videos-api:
    build:
      context: .
      dockerfile: Multimedia.Videos/Dockerfile
    depends_on:
      - ms-sql-server
    environment:
      - ConnectionStrings__VideosMultimediaDockerCS=Server=ms-sql-server,1433;Initial Catalog=VideosMultimediaDB;User ID=SA;Password=P@ssw0rd;TrustServerCertificate=true;Encrypt=False;
      - JwtToken__TokenIssuer=MultimediaVideosApi
      - JwtToken__Key=THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET, IT CAN BE ANY STRING
    volumes:
      - ./Repository_Videos:/app/Repository_Videos
    ports:
      - "8082:80"